<?php
namespace app\admin\controller;
use think\Controller;
use phpQuery\phpQuery;
use think\Loader;

class Collect extends Controller{

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub

        // 导入工具
        Loader::import('phpQuery.phpQuery.phpQuery',EXTEND_PATH);


    }

    /**
     * 页面采集
     */
    public function collectAction(){



    }
}