<?php
namespace app\index\controller;
use think\Controller;
use think\Loader;

class Wxpay extends Controller{

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub

        // 导入微信包
        Loader::import('wxpay.example.WxPayNativePay');
        Loader::import('wxpay.lib.WxPayData');
        Loader::import('wxpay.lib.WxPayConfig');
        Loader::import('wxpay.lib.WxPayApi');
        Loader::import('wxpay.lib.WxPayException');
        Loader::import('wxpay.lib.WxPayNotify');

    }

    public function indexAction(){

        return view('wxpay/index');
    }

    /**
     * 微信扫码支付(模式二)
     */
    public function payAction(){

        $params = request()->post();

        $notify = new \NativePay();

        $input = new \WxPayUnifiedOrder();

        $input->SetBody("test");
        $input->SetAttach("test");
        $input->SetOut_trade_no(\WxPayConfig::MCHID.date("YmdHis"));
        $input->SetTotal_fee("1");// 单位为:分
        $input->SetTime_start(date("YmdHis"));
        $input->SetTime_expire(date("YmdHis", time() + 600));
        $input->SetGoods_tag("test");
        $input->SetNotify_url("http://paysdk.weixin.qq.com/example/notify.php");
        $input->SetTrade_type("NATIVE");
        $input->SetProduct_id("123456789");
        $result = $notify->GetPayUrl($input);
        dump($result);exit;
        $this->assign(['url',$result["code_url"]]);

        // 组装好数据,显示订单信息给用户,并在支付按钮上绑定二维码链接
        return '<img alt="模式二扫码支付" src="/index.php?m=Home&c=Index&a=qr_code&data='.urlencode($url2).'" style="width:110px;height:110px;"/>';
    }


    /**
     * 微信客户端支付
     */
    public function getJSAPI($order){

        // 支付成功后的跳转地址
        $success = 'www.macarin.cn';
        // 支付失败的跳转地址
        $fail = 'www.baidu.com';

        //①、获取用户openid
        $tools = new \JsApiPay();
        //$openId = $tools->GetOpenid();
        $openId = $_SESSION['openid'];
        //②、统一下单
        $input = new \WxPayUnifiedOrder();
        $input->SetBody("支付订单：".$order['order_sn']);
        $input->SetAttach("weixin");
        $input->SetOut_trade_no($order['order_sn'].time());
        $input->SetTotal_fee($order['order_amount']*100);
        $input->SetTime_start(date("YmdHis"));
        $input->SetTime_expire(date("YmdHis", time() + 600));
        $input->SetGoods_tag("tp_wx_pay");
        $input->SetNotify_url('www.baidu.com');
        $input->SetTrade_type("JSAPI");
        $input->SetOpenid($openId);
        $orders = \WxPayApi::unifiedOrder($input);
        $jsApiParameters = $tools->GetJsApiParameters($orders);

        $html = <<<EOF
	<script type="text/javascript">
	//调用微信JS api 支付
	 function jsApiCall(){
		WeixinJSBridge.invoke(
			'getBrandWCPayRequest',$jsApiParameters,
			function(res){
				//WeixinJSBridge.log(res.err_msg);
				// 客户端支付成功后的跳转地址
				 if(res.err_msg == "get_brand_wcpay_request:ok") {
				    location.href='$success';
				 }else{
				 	alert(res.err_code+res.err_desc+res.err_msg);
				    location.href='$fail';
				 }
			}
		);
	}

	function callpay()
	{
		if (typeof WeixinJSBridge == "undefined"){
		    if( document.addEventListener ){
		        document.addEventListener('WeixinJSBridgeReady', jsApiCall, false);
		    }else if (document.attachEvent){
		        document.attachEvent('WeixinJSBridgeReady', jsApiCall);
		        document.attachEvent('onWeixinJSBridgeReady', jsApiCall);
		    }
		}else{
		    jsApiCall();
		}
	}
	callpay();
	</script>
EOF;
        return $html;
    }

    /**
     * 异步通知
     */

    public function notifyAction(){

        $data = request()->param();
        dump($data);

        $notify = new \PayNotifyCallBack();
        $notify->Handle(false);
        // 查询订单,修改订单状态,返回给微信端
        if('订单正确'){

            return true;
        }else{

            return false;
        }

    }

    /**
     * 同步跳转
     */
    public function returntoAction(){

        // 微信扫码支付这里没有页面返回
    }

}